### startGame
GET http://localhost:8080/startGame



### Ranking
GET http://localhost:8080/ranking?begin=0&end=4


### Post EndGame HTTP/1.1
POST http://localhost:8080/endGame 

content-Type: application/json
{
  "username": "lduc",
  "students": [  {
    "_id": "5fd0aa640dcfa0f13e3363f5",
    "name": "Bachelet Maxime",
    "sex": "F",
    "competence": 0.4613190343587375,
    "effort": 0.601308032565951,
    "speedComprehension": 0.019169410205368775,
    "analysisSpeed": 0.5390023662886667,
    "routinely": 0.7267546910308662,
    "answerAccuracy": 0.9653659783411339,
    "classAttendence": 0.006587779384487735,
    "focusness": 0.6838312565858962,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=LongHairShavedSides&accessoriesType=Round&hairColor=Platinum&facialHairType=Blank&clotheType=CollarSweater&clotheColor=Pink&eyeType=Default&eyebrowType=DefaultNatural&mouthType=Disbelief&skinColor=DarkBrown",
    "class": "B"
  },
  {
    "_id": "5fd0aa640dcfa0f13e3363f6",
    "name": "Demi L'Anglais",
    "sex": "F",
    "competence": 0.41522026575279164,
    "effort": 0.6008645811963352,
    "speedComprehension": 0.5790337014070082,
    "analysisSpeed": 0.7609219412992798,
    "routinely": 0.8372046354405351,
    "answerAccuracy": 0.494310070796675,
    "classAttendence": 0.2696109925700261,
    "focusness": 0.9688539223442472,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=LongHairMiaWallace&accessoriesType=Round&hairColor=Platinum&facialHairType=Blank&clotheType=CollarSweater&clotheColor=Blue02&eyeType=Happy&eyebrowType=Default&mouthType=Smile&skinColor=Brown",
    "class": "A"
  },
  {
    "_id": "5fd0aa640dcfa0f13e3363f7",
    "name": "Arianne Gosselin",
    "sex": "F",
    "competence": 0.2739468562079928,
    "effort": 0.7630442675928005,
    "speedComprehension": 0.9910572072088928,
    "analysisSpeed": 0.11116457385529377,
    "routinely": 0.595601138530617,
    "answerAccuracy": 0.975758611120982,
    "classAttendence": 0.6245946876431323,
    "focusness": 0.9242358853602264,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=LongHairStraight2&accessoriesType=Prescription01&hairColor=BlondeGolden&facialHairType=Blank&clotheType=CollarSweater&clotheColor=Blue01&eyeType=Default&eyebrowType=Default&mouthType=Disbelief&skinColor=DarkBrown",
    "class": "A"
  },
  {
    "_id": "5fd0aa640dcfa0f13e3363f8",
    "name": "Henry Ménard",
    "sex": "M",
    "competence": 0.45283938432103255,
    "effort": 0.4391691610023863,
    "speedComprehension": 0.4803695292269172,
    "analysisSpeed": 0.3444294818237139,
    "routinely": 0.9026891914023343,
    "answerAccuracy": 0.8780841082050674,
    "classAttendence": 0.2602984036754237,
    "focusness": 0.16726380992878376,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairFrizzle&accessoriesType=Prescription01&hairColor=Blonde&facialHairType=Blank&facialHairColor=Platinum&clotheType=CollarSweater&clotheColor=PastelGreen&eyeType=Side&eyebrowType=Default&mouthType=Default&skinColor=Light",
    "class": "A"
  },
  {
    "_id": "5fd0aa640dcfa0f13e3363f9",
    "name": "Hugh Hervieux",
    "sex": "M",
    "competence": 0.3586439430608159,
    "effort": 0.31109542381398264,
    "speedComprehension": 0.0031362373814924904,
    "analysisSpeed": 0.602727097907737,
    "routinely": 0.8237928489206756,
    "answerAccuracy": 0.8514164171029774,
    "classAttendence": 0.7552984702802206,
    "focusness": 0.797149757271409,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairShortCurly&accessoriesType=Blank&hairColor=Blonde&facialHairType=Blank&facialHairColor=BrownDark&clotheType=CollarSweater&clotheColor=PastelGreen&eyeType=Default&eyebrowType=DefaultNatural&mouthType=Twinkle&skinColor=Brown",
    "class": "A"
  },
  {
    "_id": "5fd0aa640dcfa0f13e3363fa",
    "name": "Soren Bolduc",
    "sex": "M",
    "competence": 0.40841492796583184,
    "effort": 0.4349998881108172,
    "speedComprehension": 0.2044105283815345,
    "analysisSpeed": 0.3250031443098955,
    "routinely": 0.5018217447505438,
    "answerAccuracy": 0.7388930834940011,
    "classAttendence": 0.556590998144848,
    "focusness": 0.48749224077792985,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairTheCaesar&accessoriesType=Blank&hairColor=BrownDark&facialHairType=Blank&facialHairColor=Brown&clotheType=CollarSweater&clotheColor=PastelBlue&eyeType=Side&eyebrowType=DefaultNatural&mouthType=Disbelief&skinColor=Light",
    "class": "A"
  },
  {
    "_id": "5fd0aa640dcfa0f13e3363fb",
    "name": "Seymour Rouze",
    "sex": "M",
    "competence": 0.5553446964524685,
    "effort": 0.1990674273567231,
    "speedComprehension": 0.8431365758409299,
    "analysisSpeed": 0.7772959440619023,
    "routinely": 0.020121583739929116,
    "answerAccuracy": 0.38379152193764865,
    "classAttendence": 0.6969692507013392,
    "focusness": 0.9624467074431393,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairFrizzle&accessoriesType=Blank&hairColor=Platinum&facialHairType=Blank&facialHairColor=Brown&clotheType=CollarSweater&clotheColor=Heather&eyeType=Happy&eyebrowType=DefaultNatural&mouthType=Smile&skinColor=DarkBrown",
    "class": "A"
  },
  {
    "_id": "5fd0aa640dcfa0f13e3363fc",
    "name": "Audrey Givry",
    "sex": "F",
    "competence": 0.8174710411229281,
    "effort": 0.2649593130221734,
    "speedComprehension": 0.33901548506598966,
    "analysisSpeed": 0.23917390481959155,
    "routinely": 0.13700071390751933,
    "answerAccuracy": 0.7861997892261341,
    "classAttendence": 0.6750798553773951,
    "focusness": 0.06388633968256241,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=LongHairBob&accessoriesType=Prescription02&hairColor=Brown&facialHairType=Blank&clotheType=CollarSweater&clotheColor=PastelRed&eyeType=Default&eyebrowType=Default&mouthType=Smile&skinColor=Light",
    "class": "B"
  },
  {
    "_id": "5fd0aa640dcfa0f13e3363fd",
    "name": "Demi Cadieux",
    "sex": "F",
    "competence": 0.6233048367021778,
    "effort": 0.7072025688043063,
    "speedComprehension": 0.2280417317452863,
    "analysisSpeed": 0.9446641887627423,
    "routinely": 0.40271922046222364,
    "answerAccuracy": 0.48752736021518794,
    "classAttendence": 0.8785365797553235,
    "focusness": 0.19921346699762887,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=LongHairStraightStrand&accessoriesType=Round&hairColor=Brown&facialHairType=Blank&clotheType=CollarSweater&clotheColor=Gray01&eyeType=Happy&eyebrowType=DefaultNatural&mouthType=Serious&skinColor=DarkBrown",
    "class": "B"
  },
  {
    "_id": "5fd0aa640dcfa0f13e3363fe",
    "name": "Jérôme Brisette",
    "sex": "M",
    "competence": 0.2882452817825499,
    "effort": 0.286059464587882,
    "speedComprehension": 0.1732225289974243,
    "analysisSpeed": 0.27604437246423386,
    "routinely": 0.5181295789489115,
    "answerAccuracy": 0.8836996705299405,
    "classAttendence": 0.8677895929308874,
    "focusness": 0.49255541061088715,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairDreads02&accessoriesType=Round&hairColor=BrownDark&facialHairType=Blank&facialHairColor=Black&clotheType=CollarSweater&clotheColor=Red&eyeType=Happy&eyebrowType=DefaultNatural&mouthType=Serious&skinColor=Light",
    "class": "B"
  },
  {
    "_id": "5fd0aa640dcfa0f13e3363ff",
    "name": "Henriette Neufville",
    "sex": "F",
    "competence": 0.4222609366982937,
    "effort": 0.19795622792859321,
    "speedComprehension": 0.7087730102073362,
    "analysisSpeed": 0.07920463513558973,
    "routinely": 0.9953523129149495,
    "answerAccuracy": 0.8101791320045406,
    "classAttendence": 0.053146867175416945,
    "focusness": 0.38248975718731537,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=LongHairBob&accessoriesType=Round&hairColor=BrownDark&facialHairType=Blank&clotheType=CollarSweater&clotheColor=Gray01&eyeType=Happy&eyebrowType=DefaultNatural&mouthType=Disbelief&skinColor=Black",
    "class": "B"
  },
  {
    "_id": "5fd0aa640dcfa0f13e336400",
    "name": "Azura Lacharité",
    "sex": "F",
    "competence": 0.5625451943964751,
    "effort": 0.341903741506566,
    "speedComprehension": 0.06767716446081362,
    "analysisSpeed": 0.5301477666758068,
    "routinely": 0.02884454351187693,
    "answerAccuracy": 0.6317862427848027,
    "classAttendence": 0.022683577175722114,
    "focusness": 0.15327650462741516,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=LongHairBob&accessoriesType=Blank&hairColor=Auburn&facialHairType=Blank&clotheType=CollarSweater&clotheColor=Black&eyeType=Happy&eyebrowType=DefaultNatural&mouthType=Serious&skinColor=Pale",
    "class": "B"
  },
  {
    "_id": "5fd0aa640dcfa0f13e336401",
    "name": "Lance Arcouet",
    "sex": "M",
    "competence": 0.2918119241633071,
    "effort": 0.48794428251305555,
    "speedComprehension": 0.619031098045207,
    "analysisSpeed": 0.7933378730138811,
    "routinely": 0.12718945273028304,
    "answerAccuracy": 0.23739181054870317,
    "classAttendence": 0.35684696168861674,
    "focusness": 0.8554454731669061,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairShortFlat&accessoriesType=Round&hairColor=Blonde&facialHairType=Blank&facialHairColor=BrownDark&clotheType=CollarSweater&clotheColor=Pink&eyeType=Happy&eyebrowType=DefaultNatural&mouthType=Serious&skinColor=Light",
    "class": "B"
  },
  {
    "_id": "5fd0aa640dcfa0f13e336402",
    "name": "Kerman Dufour",
    "sex": "M",
    "competence": 0.5130702057212103,
    "effort": 0.48714451840785994,
    "speedComprehension": 0.39478733187900206,
    "analysisSpeed": 0.9213236416546151,
    "routinely": 0.8747102400053568,
    "answerAccuracy": 0.5592412627823524,
    "classAttendence": 0.7783941736044164,
    "focusness": 0.6186586423117855,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairShortFlat&accessoriesType=Prescription02&hairColor=Blonde&facialHairType=Blank&facialHairColor=Platinum&clotheType=CollarSweater&clotheColor=PastelYellow&eyeType=Side&eyebrowType=DefaultNatural&mouthType=Smile&skinColor=Pale",
    "class": "B"
  },
  {
    "_id": "5fd0aa640dcfa0f13e336403",
    "name": "Gano Jardine",
    "sex": "M",
    "competence": 0.7776404166180422,
    "effort": 0.3856267428200062,
    "speedComprehension": 0.6027861891040449,
    "analysisSpeed": 0.3837598560086881,
    "routinely": 0.268522588921305,
    "answerAccuracy": 0.5056503601111799,
    "classAttendence": 0.2595052158597324,
    "focusness": 0.6414510492084067,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairShaggyMullet&accessoriesType=Prescription02&hairColor=BrownDark&facialHairType=Blank&facialHairColor=BrownDark&clotheType=CollarSweater&clotheColor=Black&eyeType=Happy&eyebrowType=DefaultNatural&mouthType=Smile&skinColor=Black",
    "class": "B"
  },
  {
    "_id": "5fd0aa640dcfa0f13e336404",
    "name": "Nicole Tanguay",
    "sex": "F",
    "competence": 0.5310052407683435,
    "effort": 0.46125583054754604,
    "speedComprehension": 0.1295250065293876,
    "analysisSpeed": 0.4505337171047743,
    "routinely": 0.9689956505000057,
    "answerAccuracy": 0.508032087833425,
    "classAttendence": 0.8966877011463574,
    "focusness": 0.9247263126196241,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=LongHairStraight2&accessoriesType=Round&hairColor=Black&facialHairType=Blank&clotheType=CollarSweater&clotheColor=Blue02&eyeType=Happy&eyebrowType=Default&mouthType=Twinkle&skinColor=Brown",
    "class": "A"
  },
  {
    "_id": "5fd0aa640dcfa0f13e336405",
    "name": "Tanguy Lapointe",
    "sex": "M",
    "competence": 0.6603265416536497,
    "effort": 0.6549338052201156,
    "speedComprehension": 0.09273208845505576,
    "analysisSpeed": 0.7445161833218323,
    "routinely": 0.9074420041499469,
    "answerAccuracy": 0.6142363305702827,
    "classAttendence": 0.5830632300113783,
    "focusness": 0.8279911109894724,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairShortRound&accessoriesType=Prescription01&hairColor=BrownDark&facialHairType=Blank&facialHairColor=Platinum&clotheType=CollarSweater&clotheColor=Blue01&eyeType=Happy&eyebrowType=DefaultNatural&mouthType=Default&skinColor=DarkBrown",
    "class": "A"
  },
  {
    "_id": "5fd0aa640dcfa0f13e336406",
    "name": "Marcel Casgrain",
    "sex": "M",
    "competence": 0.5870306749076363,
    "effort": 0.669542660115996,
    "speedComprehension": 0.46074211526424236,
    "analysisSpeed": 0.42811824543474675,
    "routinely": 0.5444154232770493,
    "answerAccuracy": 0.48907609095388027,
    "classAttendence": 0.7213472494633324,
    "focusness": 0.2360078068254745,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairShortRound&accessoriesType=Round&hairColor=Blonde&facialHairType=Blank&facialHairColor=BlondeGolden&clotheType=CollarSweater&clotheColor=Blue03&eyeType=Default&eyebrowType=DefaultNatural&mouthType=Twinkle&skinColor=DarkBrown",
    "class": "B"
  },
  {
    "_id": "5fd0aa640dcfa0f13e336407",
    "name": "Chappell Trudeau",
    "sex": "M",
    "competence": 0.12743081014677649,
    "effort": 0.6369511318060784,
    "speedComprehension": 0.8279914256429068,
    "analysisSpeed": 0.8420046767407479,
    "routinely": 0.5954055320887448,
    "answerAccuracy": 0.11923448061838893,
    "classAttendence": 0.37630434809681135,
    "focusness": 0.8650230055183701,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairDreads02&accessoriesType=Prescription02&hairColor=Brown&facialHairType=Blank&facialHairColor=BlondeGolden&clotheType=CollarSweater&clotheColor=PastelGreen&eyeType=Default&eyebrowType=Default&mouthType=Serious&skinColor=Black",
    "class": "B"
  },
  {
    "_id": "5fd0aa640dcfa0f13e336408",
    "name": "Victor Jobin",
    "sex": "M",
    "competence": 0.7001770214622005,
    "effort": 0.4052139308262302,
    "speedComprehension": 0.5266748616864134,
    "analysisSpeed": 0.9071047493501652,
    "routinely": 0.5743074407397801,
    "answerAccuracy": 0.9066651552689335,
    "classAttendence": 0.621577130633189,
    "focusness": 0.7447193607828158,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairShortFlat&accessoriesType=Prescription01&hairColor=Auburn&facialHairType=Blank&facialHairColor=Brown&clotheType=CollarSweater&clotheColor=Blue01&eyeType=Default&eyebrowType=Default&mouthType=Twinkle&skinColor=Black",
    "class": "B"
  },
  {
    "_id": "5fd0aa640dcfa0f13e336409",
    "name": "Gaston Lefèbvre",
    "sex": "M",
    "competence": 0.8732234415518115,
    "effort": 0.5674625343809118,
    "speedComprehension": 0.35319716858580197,
    "analysisSpeed": 0.5635873852768105,
    "routinely": 0.48577042970183104,
    "answerAccuracy": 0.6151092580613153,
    "classAttendence": 0.15632293054665536,
    "focusness": 0.4655415724826799,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairShortRound&accessoriesType=Prescription01&hairColor=Brown&facialHairType=Blank&facialHairColor=BlondeGolden&clotheType=CollarSweater&clotheColor=Heather&eyeType=Default&eyebrowType=DefaultNatural&mouthType=Twinkle&skinColor=Brown",
    "class": "B"
  },
  {
    "_id": "5fd0aa640dcfa0f13e33640a",
    "name": "Isaac Grandpré",
    "sex": "M",
    "competence": 0.4998280136362429,
    "effort": 0.4208564112997872,
    "speedComprehension": 0.4406144271189585,
    "analysisSpeed": 0.9976443270271103,
    "routinely": 0.02097112451087768,
    "answerAccuracy": 0.02132749525123967,
    "classAttendence": 0.791285847652712,
    "focusness": 0.29948705588920643,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairTheCaesar&accessoriesType=Prescription02&hairColor=Platinum&facialHairType=Blank&facialHairColor=Platinum&clotheType=CollarSweater&clotheColor=PastelRed&eyeType=Side&eyebrowType=DefaultNatural&mouthType=Disbelief&skinColor=Brown",
    "class": "A"
  },
  {
    "_id": "5fd0aa640dcfa0f13e33640b",
    "name": "Aimé Larivière",
    "sex": "M",
    "competence": 0.6337335052712932,
    "effort": 0.7742421874758524,
    "speedComprehension": 0.3999778244477612,
    "analysisSpeed": 0.9079433371351422,
    "routinely": 0.6408167081078509,
    "answerAccuracy": 0.37476194816219577,
    "classAttendence": 0.6691868680998085,
    "focusness": 0.7345614771837772,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairDreads02&accessoriesType=Prescription01&hairColor=Blonde&facialHairType=Blank&facialHairColor=Blonde&clotheType=CollarSweater&clotheColor=Pink&eyeType=Default&eyebrowType=DefaultNatural&mouthType=Serious&skinColor=DarkBrown",
    "class": "B"
  },
  {
    "_id": "5fd0aa640dcfa0f13e33640c",
    "name": "Dexter Sauvé",
    "sex": "M",
    "competence": 0.3505811039975609,
    "effort": 0.6130911296594667,
    "speedComprehension": 0.11525900004480127,
    "analysisSpeed": 0.45804908006320355,
    "routinely": 0.014851262353373418,
    "answerAccuracy": 0.2798501482093887,
    "classAttendence": 0.19148772462446906,
    "focusness": 0.5633742690995696,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=ShortHairShaggyMullet&accessoriesType=Round&hairColor=BlondeGolden&facialHairType=Blank&facialHairColor=Blonde&clotheType=CollarSweater&clotheColor=PastelGreen&eyeType=Side&eyebrowType=Default&mouthType=Disbelief&skinColor=Black",
    "class": "B"
  },
  {
    "_id": "5fd0aa640dcfa0f13e33640d",
    "name": "Logistilla Riel",
    "sex": "F",
    "competence": 0.6383348455061196,
    "effort": 0.6111527798441723,
    "speedComprehension": 0.10800104443864811,
    "analysisSpeed": 0.9162727999345666,
    "routinely": 0.09455596329922145,
    "answerAccuracy": 0.42674751561413204,
    "classAttendence": 0.010241087330659537,
    "focusness": 0.21473078119894273,
    "img": "https://avataaars.io/?avatarStyle=Transparent&topType=LongHairStraight2&accessoriesType=Prescription02&hairColor=Auburn&facialHairType=Blank&clotheType=CollarSweater&clotheColor=Pink&eyeType=Side&eyebrowType=DefaultNatural&mouthType=Disbelief&skinColor=Black",
    "class": "A"
  }],
  "teacherA": 
  {
    "_id": "5fc12e5abb6c5e863d1349c1",
    "name": "Mme Burckel",
    "sex": "F",
    "anneeEtude": 7,
    "age": 33,
    "experience": 4,
    "jugementCompetence": 1,
    "jugementEffort": 1,
    "description": "Mme Massé est une enseignante qui valorise les competences mais aussi les efforts.",
    "img": "https://avataaars.io/?avatarStyle=Circle&topType=LongHairNotTooLong&accessoriesType=Prescription01&hairColor=Brown&facialHairType=Blank&clotheType=CollarSweater&clotheColor=Black&eyeType=Side&eyebrowType=DefaultNatural&mouthType=Twinkle&skinColor=Brown",
    "class": "A"

  },
  "teacherB":   {
    "_id": "5fc12e5abb6c5e863d1349c4",
    "name": "Mme Bachelet",
    "sex": "F",
    "anneeEtude": 5,
    "age": 51,
    "experience": 24,
    "jugementCompetence": 1,
    "jugementEffort": 0,
    "description": "Mme Riel est une enseignante qui ne valorise que les competences.",
    "img": "https://avataaars.io/?avatarStyle=Circle&topType=LongHairFrida&accessoriesType=Prescription02&hairColor=Black&facialHairType=Blank&clotheType=ShirtCrewNeck&clotheColor=PastelBlue&eyeType=Side&eyebrowType=DefaultNatural&mouthType=Serious&skinColor=Pale",
    "class": "B"
  }
}



